@endpoint = https://nrisdk1ahf.execute-api.us-east-1.amazonaws.com/dev/notes

GET {{endpoint}}
###

POST {{endpoint}}
Content-Type: application/json

{
 "id": "2",
 "title": "title",
 "body": "body"
}
###

PUT {{endpoint}}/1
Content-Type:  application/json

{
    "title": "new title",
    "body": "new body"
}

###

DELETE  {{endpoint}}/1